override_args:
  total_timesteps: 50000
  buffer_size: 50000
  learning_starts: 10000


train:
  l:
    context_space_type: categorical
    choices: [0.7, 0.9, 1.1, 1.3]
  m:
    context_space_type: categorical
    choices: [0.7, 0.9, 1.1, 1.3]

train_wide:
  l:
    context_space_type: categorical
    choices: [0.5, 0.7, 0.9, 1.1, 1.3, 1.5]
  m:
    context_space_type: categorical
    choices: [0.5, 0.7, 0.9, 1.1, 1.3, 1.5]


test:
  l:
    context_space_type: categorical
    choices: [0.1, 0.3, 0.5, 0.7, 0.9, 1.1, 1.3, 1.5, 1.7, 1.9]
  m:
    context_space_type: categorical
    choices: [0.1, 0.3, 0.5, 0.7, 0.9, 1.1, 1.3, 1.5, 1.7, 1.9]

test_1:
  l:
    context_space_type: categorical
    choices: [0.1]
  m:
    context_space_type: categorical
    choices: [0.1]

test_2:
  l:
    context_space_type: categorical
    choices: [0.1]
  m:
    context_space_type: categorical
    choices: [0.3]

test_3:
  l:
    context_space_type: categorical
    choices: [0.1]
  m:
    context_space_type: categorical
    choices: [0.5]

test_4:
  l:
    context_space_type: categorical
    choices: [0.1]
  m:
    context_space_type: categorical
    choices: [0.7]

test_5:
  l:
    context_space_type: categorical
    choices: [0.1]
  m:
    context_space_type: categorical
    choices: [0.9]

test_6:
  l:
    context_space_type: categorical
    choices: [0.1]
  m:
    context_space_type: categorical
    choices: [1.1]

test_7:
  l:
    context_space_type: categorical
    choices: [0.1]
  m:
    context_space_type: categorical
    choices: [1.3]

test_8:
  l:
    context_space_type: categorical
    choices: [0.1]
  m:
    context_space_type: categorical
    choices: [1.5]

test_9:
  l:
    context_space_type: categorical
    choices: [0.1]
  m:
    context_space_type: categorical
    choices: [1.7]

test_10:
  l:
    context_space_type: categorical
    choices: [0.1]
  m:
    context_space_type: categorical
    choices: [1.9]

test_11:
  l:
    context_space_type: categorical
    choices: [0.3]
  m:
    context_space_type: categorical
    choices: [0.1]

test_12:
  l:
    context_space_type: categorical
    choices: [0.3]
  m:
    context_space_type: categorical
    choices: [0.3]

test_13:
  l:
    context_space_type: categorical
    choices: [0.3]
  m:
    context_space_type: categorical
    choices: [0.5]

test_14:
  l:
    context_space_type: categorical
    choices: [0.3]
  m:
    context_space_type: categorical
    choices: [0.7]

test_15:
  l:
    context_space_type: categorical
    choices: [0.3]
  m:
    context_space_type: categorical
    choices: [0.9]

test_16:
  l:
    context_space_type: categorical
    choices: [0.3]
  m:
    context_space_type: categorical
    choices: [1.1]

test_17:
  l:
    context_space_type: categorical
    choices: [0.3]
  m:
    context_space_type: categorical
    choices: [1.3]

test_18:
  l:
    context_space_type: categorical
    choices: [0.3]
  m:
    context_space_type: categorical
    choices: [1.5]

test_19:
  l:
    context_space_type: categorical
    choices: [0.3]
  m:
    context_space_type: categorical
    choices: [1.7]

test_20:
  l:
    context_space_type: categorical
    choices: [0.3]
  m:
    context_space_type: categorical
    choices: [1.9]

test_21:
  l:
    context_space_type: categorical
    choices: [0.5]
  m:
    context_space_type: categorical
    choices: [0.1]

test_22:
  l:
    context_space_type: categorical
    choices: [0.5]
  m:
    context_space_type: categorical
    choices: [0.3]

test_23:
  l:
    context_space_type: categorical
    choices: [0.5]
  m:
    context_space_type: categorical
    choices: [0.5]

test_24:
  l:
    context_space_type: categorical
    choices: [0.5]
  m:
    context_space_type: categorical
    choices: [0.7]

test_25:
  l:
    context_space_type: categorical
    choices: [0.5]
  m:
    context_space_type: categorical
    choices: [0.9]

test_26:
  l:
    context_space_type: categorical
    choices: [0.5]
  m:
    context_space_type: categorical
    choices: [1.1]

test_27:
  l:
    context_space_type: categorical
    choices: [0.5]
  m:
    context_space_type: categorical
    choices: [1.3]

test_28:
  l:
    context_space_type: categorical
    choices: [0.5]
  m:
    context_space_type: categorical
    choices: [1.5]

test_29:
  l:
    context_space_type: categorical
    choices: [0.5]
  m:
    context_space_type: categorical
    choices: [1.7]

test_30:
  l:
    context_space_type: categorical
    choices: [0.5]
  m:
    context_space_type: categorical
    choices: [1.9]

test_31:
  l:
    context_space_type: categorical
    choices: [0.7]
  m:
    context_space_type: categorical
    choices: [0.1]

test_32:
  l:
    context_space_type: categorical
    choices: [0.7]
  m:
    context_space_type: categorical
    choices: [0.3]

test_33:
  l:
    context_space_type: categorical
    choices: [0.7]
  m:
    context_space_type: categorical
    choices: [0.5]

test_34:
  l:
    context_space_type: categorical
    choices: [0.7]
  m:
    context_space_type: categorical
    choices: [0.7]

test_35:
  l:
    context_space_type: categorical
    choices: [0.7]
  m:
    context_space_type: categorical
    choices: [0.9]

test_36:
  l:
    context_space_type: categorical
    choices: [0.7]
  m:
    context_space_type: categorical
    choices: [1.1]

test_37:
  l:
    context_space_type: categorical
    choices: [0.7]
  m:
    context_space_type: categorical
    choices: [1.3]

test_38:
  l:
    context_space_type: categorical
    choices: [0.7]
  m:
    context_space_type: categorical
    choices: [1.5]

test_39:
  l:
    context_space_type: categorical
    choices: [0.7]
  m:
    context_space_type: categorical
    choices: [1.7]

test_40:
  l:
    context_space_type: categorical
    choices: [0.7]
  m:
    context_space_type: categorical
    choices: [1.9]

test_41:
  l:
    context_space_type: categorical
    choices: [0.9]
  m:
    context_space_type: categorical
    choices: [0.1]

test_42:
  l:
    context_space_type: categorical
    choices: [0.9]
  m:
    context_space_type: categorical
    choices: [0.3]

test_43:
  l:
    context_space_type: categorical
    choices: [0.9]
  m:
    context_space_type: categorical
    choices: [0.5]

test_44:
  l:
    context_space_type: categorical
    choices: [0.9]
  m:
    context_space_type: categorical
    choices: [0.7]

test_45:
  l:
    context_space_type: categorical
    choices: [0.9]
  m:
    context_space_type: categorical
    choices: [0.9]

test_46:
  l:
    context_space_type: categorical
    choices: [0.9]
  m:
    context_space_type: categorical
    choices: [1.1]

test_47:
  l:
    context_space_type: categorical
    choices: [0.9]
  m:
    context_space_type: categorical
    choices: [1.3]

test_48:
  l:
    context_space_type: categorical
    choices: [0.9]
  m:
    context_space_type: categorical
    choices: [1.5]

test_49:
  l:
    context_space_type: categorical
    choices: [0.9]
  m:
    context_space_type: categorical
    choices: [1.7]

test_50:
  l:
    context_space_type: categorical
    choices: [0.9]
  m:
    context_space_type: categorical
    choices: [1.9]

test_51:
  l:
    context_space_type: categorical
    choices: [1.1]
  m:
    context_space_type: categorical
    choices: [0.1]

test_52:
  l:
    context_space_type: categorical
    choices: [1.1]
  m:
    context_space_type: categorical
    choices: [0.3]

test_53:
  l:
    context_space_type: categorical
    choices: [1.1]
  m:
    context_space_type: categorical
    choices: [0.5]

test_54:
  l:
    context_space_type: categorical
    choices: [1.1]
  m:
    context_space_type: categorical
    choices: [0.7]

test_55:
  l:
    context_space_type: categorical
    choices: [1.1]
  m:
    context_space_type: categorical
    choices: [0.9]

test_56:
  l:
    context_space_type: categorical
    choices: [1.1]
  m:
    context_space_type: categorical
    choices: [1.1]

test_57:
  l:
    context_space_type: categorical
    choices: [1.1]
  m:
    context_space_type: categorical
    choices: [1.3]

test_58:
  l:
    context_space_type: categorical
    choices: [1.1]
  m:
    context_space_type: categorical
    choices: [1.5]

test_59:
  l:
    context_space_type: categorical
    choices: [1.1]
  m:
    context_space_type: categorical
    choices: [1.7]

test_60:
  l:
    context_space_type: categorical
    choices: [1.1]
  m:
    context_space_type: categorical
    choices: [1.9]

test_61:
  l:
    context_space_type: categorical
    choices: [1.3]
  m:
    context_space_type: categorical
    choices: [0.1]

test_62:
  l:
    context_space_type: categorical
    choices: [1.3]
  m:
    context_space_type: categorical
    choices: [0.3]

test_63:
  l:
    context_space_type: categorical
    choices: [1.3]
  m:
    context_space_type: categorical
    choices: [0.5]

test_64:
  l:
    context_space_type: categorical
    choices: [1.3]
  m:
    context_space_type: categorical
    choices: [0.7]

test_65:
  l:
    context_space_type: categorical
    choices: [1.3]
  m:
    context_space_type: categorical
    choices: [0.9]

test_66:
  l:
    context_space_type: categorical
    choices: [1.3]
  m:
    context_space_type: categorical
    choices: [1.1]

test_67:
  l:
    context_space_type: categorical
    choices: [1.3]
  m:
    context_space_type: categorical
    choices: [1.3]

test_68:
  l:
    context_space_type: categorical
    choices: [1.3]
  m:
    context_space_type: categorical
    choices: [1.5]

test_69:
  l:
    context_space_type: categorical
    choices: [1.3]
  m:
    context_space_type: categorical
    choices: [1.7]

test_70:
  l:
    context_space_type: categorical
    choices: [1.3]
  m:
    context_space_type: categorical
    choices: [1.9]

test_71:
  l:
    context_space_type: categorical
    choices: [1.5]
  m:
    context_space_type: categorical
    choices: [0.1]

test_72:
  l:
    context_space_type: categorical
    choices: [1.5]
  m:
    context_space_type: categorical
    choices: [0.3]

test_73:
  l:
    context_space_type: categorical
    choices: [1.5]
  m:
    context_space_type: categorical
    choices: [0.5]

test_74:
  l:
    context_space_type: categorical
    choices: [1.5]
  m:
    context_space_type: categorical
    choices: [0.7]

test_75:
  l:
    context_space_type: categorical
    choices: [1.5]
  m:
    context_space_type: categorical
    choices: [0.9]

test_76:
  l:
    context_space_type: categorical
    choices: [1.5]
  m:
    context_space_type: categorical
    choices: [1.1]

test_77:
  l:
    context_space_type: categorical
    choices: [1.5]
  m:
    context_space_type: categorical
    choices: [1.3]

test_78:
  l:
    context_space_type: categorical
    choices: [1.5]
  m:
    context_space_type: categorical
    choices: [1.5]

test_79:
  l:
    context_space_type: categorical
    choices: [1.5]
  m:
    context_space_type: categorical
    choices: [1.7]

test_80:
  l:
    context_space_type: categorical
    choices: [1.5]
  m:
    context_space_type: categorical
    choices: [1.9]

test_81:
  l:
    context_space_type: categorical
    choices: [1.7]
  m:
    context_space_type: categorical
    choices: [0.1]

test_82:
  l:
    context_space_type: categorical
    choices: [1.7]
  m:
    context_space_type: categorical
    choices: [0.3]

test_83:
  l:
    context_space_type: categorical
    choices: [1.7]
  m:
    context_space_type: categorical
    choices: [0.5]

test_84:
  l:
    context_space_type: categorical
    choices: [1.7]
  m:
    context_space_type: categorical
    choices: [0.7]

test_85:
  l:
    context_space_type: categorical
    choices: [1.7]
  m:
    context_space_type: categorical
    choices: [0.9]

test_86:
  l:
    context_space_type: categorical
    choices: [1.7]
  m:
    context_space_type: categorical
    choices: [1.1]

test_87:
  l:
    context_space_type: categorical
    choices: [1.7]
  m:
    context_space_type: categorical
    choices: [1.3]

test_88:
  l:
    context_space_type: categorical
    choices: [1.7]
  m:
    context_space_type: categorical
    choices: [1.5]

test_89:
  l:
    context_space_type: categorical
    choices: [1.7]
  m:
    context_space_type: categorical
    choices: [1.7]

test_90:
  l:
    context_space_type: categorical
    choices: [1.7]
  m:
    context_space_type: categorical
    choices: [1.9]

test_91:
  l:
    context_space_type: categorical
    choices: [1.9]
  m:
    context_space_type: categorical
    choices: [0.1]

test_92:
  l:
    context_space_type: categorical
    choices: [1.9]
  m:
    context_space_type: categorical
    choices: [0.3]

test_93:
  l:
    context_space_type: categorical
    choices: [1.9]
  m:
    context_space_type: categorical
    choices: [0.5]

test_94:
  l:
    context_space_type: categorical
    choices: [1.9]
  m:
    context_space_type: categorical
    choices: [0.7]

test_95:
  l:
    context_space_type: categorical
    choices: [1.9]
  m:
    context_space_type: categorical
    choices: [0.9]

test_96:
  l:
    context_space_type: categorical
    choices: [1.9]
  m:
    context_space_type: categorical
    choices: [1.1]

test_97:
  l:
    context_space_type: categorical
    choices: [1.9]
  m:
    context_space_type: categorical
    choices: [1.3]

test_98:
  l:
    context_space_type: categorical
    choices: [1.9]
  m:
    context_space_type: categorical
    choices: [1.5]

test_99:
  l:
    context_space_type: categorical
    choices: [1.9]
  m:
    context_space_type: categorical
    choices: [1.7]

test_100:
  l:
    context_space_type: categorical
    choices: [1.9]
  m:
    context_space_type: categorical
    choices: [1.9]